// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"time"
)

type Answer struct {
	ID         string
	QuestionID string
	Content    string
	Upvotes    int64
	Downvotes  int64
	CreatedAt  int64
	UpdatedAt  int64
}

type Question struct {
	ID        string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserSub   string
	UserName  string
	UserEmail string
	Upvotes   int64
	Downvotes int64
	Title     string
	Body      string
}
