package constants

const (
	ENV_KEY_IS_DB_LOCAL       = "IS_DB_LOCAL"
	ENV_KEY_IS_LOCAL          = "IS_LOCAL"
	ENV_KEY_TURSO_DB_PORT     = "TURSO_DB_PORT"
	ENV_KEY_TURSO_DB_TOKEN    = "TURSO_DB_TOKEN"
	ENV_KEY_TURSO_DB_HOST     = "TURSO_DB_HOST"
	ENV_KEY_TURSO_DB_NAME     = "TURSO_DB_NAME"
	ENV_KEY_TURSO_DB_PROTOCOL = "TURSO_DB_PROTOCOL"
)
